### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by rgerkin** [scidash/sciunit#101]
@appukuttan-shailesh 
Can you pull the dev branch of sciunit and see if there is anything that isn't working for you?  If there are, please open issues here, and once everything is resolved I will tag a new release on pypi.

**Comment by appukuttan-shailesh** [comment]
I ran a few of our UseCases yesteday and today with the SciUnit dev branch, and everything was running fine. I think we are good to go for the next release. I will run the entire batch of validations in the coming days (after the release) and report if I find any issues.

You had mentioned that several new features had been implemented towards this release. I have been tracking some of these here on GitHub, but would you be having a listing of all the new changes? Or can I find these in the documentation for the new release?

**Comment by rgerkin** [comment]
@appukuttan-shailesh The new release is [here](https://pypi.org/project/sciunit/0.2.1/) and the release notes are [here](https://github.com/scidash/sciunit/releases/tag/0.2.1).
