### ISSUE TITLE
Proposed: Deprecate Python 2.7

### ISSUE THREAD

**Issue by rgerkin** [scidash/sciunit#118]
See [here](https://www.python.org/doc/sunset-python-2/) for motivation.

**Comment by rgerkin** [comment]
Paging the executive committee: @JustasB @appukuttan-shailesh @scrook @cyrus- @rgutzen @apdavison @gidili @rgerkin 
Could you vote here on this issue (thumbs up emoji for yes, thumbs down emoji for no, "meh" emoji for not sure).

**Comment by ChihweiLHBird** [comment]
I found some code in `utils.py` that still support Python 2. May I remove them?

**Comment by rgerkin** [comment]
@ChihweiLHBird Yes.

**Comment by rgerkin** [comment]
Mostly done in 9fe0510164a3a98281c1eed22052ba8b2db4cae7.  The remaining attempts at Python 2 found elsewhere can be handled case-by-case.
