### ISSUE TITLE
sciunit ScoreArray does not have an iterable .items() method/attribute.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/sciunit#125]
Meaning that you can't iterate over keys and values very naturally.
sciunit ScoreArray does not have an iterable .items() method/attribute.
```python
       SM = ScoreArray(tests, scores_)
        for test,score in zip(SM.keys(),SM.values):
            error = np.abs(1.0 - np.abs(score.log_norm_score))
            dtc.errors[str(test.name)] = error
        dtc.SM = SM
```

**Comment by rgerkin** [comment]
@russelljjarvis 
This should work (with no additional changes):
```
import sciunit
from sciunit.models.examples import UniformModel
from sciunit.tests import RangeTest
from sciunit.scores.collections import ScoreArray

m = UniformModel(2, 3)
t1 = RangeTest([2,3])
t2 = RangeTest([4,5])
suite = sciunit.TestSuite([t1, t2])
score_matrix = suite.judge(m)
```
`TestSuite.judge` always returns a `ScoreMatrix`.  Now slice a `ScoreArray` out of it, and iterate over its items.
```
score_array = score_matrix[m]
for test, score in score_array.items():
    print(test, score)
```
Alternative, construct a new `ScoreArray` from scratch (here I use the old `ScoreArray`s values for convenience, but any scores will do, as long as they are `Score` objects.
```
new_score_array = ScoreArray([t1, t2], score_array.values)
```
And you can iterate over its items in the same way.
```
for test, score in new_score_array.items():
    print(test, score)
```

**Comment by russelljjarvis** [comment]
Okay, i have updated code so I slice an array out of the matrix.
