### ISSUE TITLE
Resolve sciunit.base.LOGGING vs sciunit.utils.settings['LOGGING']

### ISSUE THREAD

**Issue by rgerkin** [scidash/sciunit#130]
There can be only one ⚔️.

**Comment by rgerkin** [comment]
@ChihweiLHBird There are two locations where I have a setting concerning logging.  Could you determine which of these is actually used elsewhere (if either), and make a decision about which one to keep (and remove the other one)?

**Comment by ChihweiLHBird** [comment]
From this search result page, https://github.com/scidash/sciunit/search?q=LOGGING, we can see that `sciunit.base.LOGGING` was never used in the SciUnit project (except where it is defined), and `sciunit.utils.settings['LOGGING']` was used in `log` function in `sciunit.utils`. My suggestion is deleting `sciunit.base.LOGGING`. I did it locally and it passed all the unit test cases.

**Comment by ChihweiLHBird** [comment]
https://github.com/scidash/sciunit/pull/150
This is the pull request to remove sciunit.base.LOGGING and update some docstrings.

**Comment by ChihweiLHBird** [comment]
Fixed in a442c81a34b382e888077b5fbbcbdec6b838f389
