### ISSUE TITLE
v0.2.7 not tagged

### ISSUE THREAD

**Issue by sanjayankur31** [scidash/sciunit#208]
Hello,

I was looking to update the [NeuroFedora sciunit package](https://src.fedoraproject.org/rpms/python-sciunit), and we use tags to fetch the sources which failed. I *think* it's because the v0.2.7 release is missing in the tag list:

https://github.com/scidash/sciunit/tags

**Comment by rgerkin** [comment]
@sanjayankur31 v0.2.7 now added to tags: https://github.com/scidash/sciunit/tags.
