### ISSUE TITLE
inspect.getargspec deprecated in Python 3

### ISSUE THREAD

**Issue by sanjayankur31** [scidash/sciunit#209]
... and it's been removed in Python 3.11:

https://docs.python.org/3.11/whatsnew/3.11.html?highlight=inspect%20signature#removed

We need to use signature or getfullargspec instead:

```
sed -i 's/) = inspect.getargspec/, _, _, _) = inspect.getfullargspec/' sciunit/utils.py
```

**Comment by rgerkin** [comment]
Would you like to submit a PR for this?  We would be happy to have your contribution.  If not, I'll take care of it.

**Comment by sanjayankur31** [comment]
Sure, opened #210 . Since I'm building for py3.11 now, I was hoping to also enable that in CI, but I don't think 3.11 is available on GH actions yet, so we'll have to wait a bit for that.
