### ISSUE TITLE
CellExecutionError no longer available in nbconvert.preprocessors.execute (nbconvert 7.13.0)

### ISSUE THREAD

**Issue by frenzymadness** [scidash/sciunit#220]
This line has to be changed to make sciunit compatible with nbconvert 7.13.0:

https://github.com/scidash/sciunit/blob/c00b21768edbe1cd734dd1c85f967e2fde136ec3/sciunit/utils.py#L29

See this change: https://github.com/jupyter/nbconvert/commit/a7df9afbf165e397c31d6b79c66cff8288e4a42e#diff-bee04d71b1dfc0202a0239b1513fd81d983edc339a9734ca4f4813276feed032 

IIUC, the class should be imported from nbclient instead.

**Comment by rgerkin** [comment]
@frenzymadness Could you submit a PR for this?

**Comment by frenzymadness** [comment]
One more thing to consider that I realized now is that we might want to add nbclient as an explicit dependency. nbconvert depends on nbclient so it will work but if we import from nbclient it should be required explicitly IMHO.
