### ISSUE TITLE
Update importlib-metadata requirement

### ISSUE THREAD

**Issue by rgutzen** [scidash/sciunit#222]
Currently, sciunit requires `importlib-metadata<4.0`. However, importlib-metadata now is in version 7.0.0. and many other packages require more recent versions of this package. For example, jupyterlab has a requirement `importlib-metadata >= 4.8.3`. This makes it difficult to install sciunit together in an environment with such packages.
I also couldn't directly figure out where sciunit requires this specific older version. Maybe, this could be updated to make sciunit, and its derived packages, easier to integrate in various environments?
This incompatibility was discovered by, and is therefore also of interest for, @heplesser.

**Comment by rgerkin** [comment]
If all tests pass with that requirement changed or relaxed, I'd be happy to accept a PR.

**Comment by rgerkin** [comment]
Fixed in #223.
