### ISSUE TITLE
setup.py installation problems

### ISSUE THREAD

**Issue by robclewley** [scidash/sciunit#25]
Installing on python 2.7, two issues arise:

1) Warning
/sw/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'

2) Error:
error: package directory 'sciunit/test' does not exist

I think you mean to say sciunit.tests (plural) in setup.py

**Comment by rgerkin** [comment]
Thanks, it should be fixed now.
