### ISSUE TITLE
Desired way to incorporate my specific Dockerfile contents into scidash/dockerstacks 

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/sciunit#40]
I need to find a way to include my DEAP[ build tweaks from my Dockerfile](https://github.com/scidash/neuronunit/blob/dev/neuronunit/tests/Dockerfile) into scidash/dockerstacks and then push this to docker hub, such that my travis builds run faster.

@rgerkin  I feel that you may have already added in some changes to docker-stacks, or that you may have created a fast work around that enables you to quickly run my code?

**Comment by rgerkin** [comment]
Probably not relevant to sciunit per se.
