### ISSUE TITLE
Trying to catch obscure math domain error. 

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/sciunit#41]
I am trying to catch a certain math error that occurs not regularly but periodically as the GA samples different parameters on subsequent runs due to the PRNG.

I feel that the sanity_check method should be able to stop these math errors if it is done well. I am unsure if I am being too picky by throwing out cases when the membrane potential doesn't change at all (its derivative is full of zero's).

Something else I have noticed is that if the rheobase current is found to be exactly 0 Amps, compute score fails for the Rheobase test, also I think due to a math error. I have put in a short term hack where a rheobase that is found to be exactly 0Amp is substituted for 0.0000001Amp instead.

```
    def sanity_check(self,rheobase,model):
        '''
        check if the membrane potential and its derivative, constitute continuous differentiable
        functions
        If they don't output boolean false, such that the corresponding model can be discarded
        inputs: a rheobase value and a model.
        outputs: a boolean flag.
        '''
        self.params['injected_square_current']['delay'] = DELAY
        self.params['injected_square_current']['duration'] = DURATION
        self.params['injected_square_current']['amplitude'] = rheobase
        model.inject_square_current(self.params['injected_square_current'])
        mp = model.results['vm']
        def nan_test(mp):
            import numpy as np
            #is the membrane potential filled with 0's
            if np.array(mp).all(0)==True:
                return False

            import math
            #is the membrane potential containing nans's

            for i in mp:            
                if math.isnan(i):
                    return False

            import neuronunit.capabilities as cap
            sws = cap.spike_functions.get_spike_waveforms(model.get_membrane_potential())
            #is the membrane potential derivative containing nans's?

            for i,s in enumerate(sws):
                s = np.array(s)
                dvdt = np.diff(s)
                import math
                for j in dvdt:
                    if math.isnan(j):
                        return False

            diffarrray = [ np.diff(np.array(s)) for i,s in enumerate(sws)]
            #is the derivative of the membrane potential filled with 0's

            if np.array(diffarrray).all(0)==True
                return False


        boolean = nan_test(mp)
        if boolean == False:
            return False
```

**Comment by rgerkin** [comment]
@russelljjarvis 
The rheobase can technically be negative, because for some model parameters the cell is spontaneously spiking and so one would have to inject negative current to quiet it down to 1 or 0 spikes.  So actually the lower bound on the current injected shouldn't be 0 it should be something like -200 pA.  

I think your entire `nan_test` just be:
```
def nan_test(mp):
  x = mp.std()
  return np.isnan(x) or x==0
```
It will return `True` if x has any NaNs in it, or if it has any infinities, or if it is filled with the same value throughout (i.e. zero derivative), and `False` otherwise

**Comment by russelljjarvis** [comment]
This is great! I love it when someone is able to reduce 30 lines of code to 3.

**Comment by russelljjarvis** [comment]
This is still a problem. The stack trace is as follows:
```
Executing test RheobaseTest on model vanilla vr-60.0093546503 a0.0302490425576 b-2.17834882988e-08 C0.000100856233988 c-56.7549730011 d0.131391774118 v0-59.2556471371 k0.000936021173602 vt-37.5156195525 vpeak25.9458285474... Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_control.py", line 150, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/opt/conda/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/conda/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/conda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "nsga.py", line 463, in <module>
    pop, stats = main()
  File "nsga.py", line 331, in main
    fitnesses = list(toolbox.map(toolbox.evaluate, pop, iter_))
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 99, in _mapGenerator
    for future in _waitAll(*futures):
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 360, in _waitAll
    for f in _waitAny(future):
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 337, in _waitAny
    raise childFuture.exceptionValue
ValueError: math domain error

Executing test RheobaseTest on model vanilla... Executing test RheobaseTest on model vanilla... [2017-04-05 19:31:15,122] launcher  (127.0.0.1:40880) INFO    Root process is done.
[2017-04-05 19:31:15,122] launcher  (127.0.0.1:40880) INFO    Finished cleaning spawned subprocesses.
```

**Comment by russelljjarvis** [comment]
```
Executing test RheobaseTest on model vanilla... (<grid_search.VirtualModel object at 0x7fc978cd4630>, 0.0)
<grid_search.VirtualModel object at 0x7fc978cd4630> 0.0
0.0
```

I have since found that this error occurs when the rheobase test acts on an absence of injected current. current injection 0Amps causes 1 spike, so it is fed in as a model prediction to the neuronunit Rheobase tests suite. I am guessing that the way the corresponding z-score is derived cannot deal with 0 as prediction argument.

**Comment by rgerkin** [comment]
@russelljjarvis 
The predicted value never appears in the denominator (in `RatioScore` or `ZScore`) so I don't see where that would produce a math error.  Other possibilities are the `sqrt` or `log` of negative number.  I think you got rid of the `math` module when you switched to my simpler code above that uses `numpy`.  So the `math` error must be from some other use of the `math` module.  The `sort_key` for `ZScore` has this:  
```
cdf = (1.0 + math.erf(self.score / math.sqrt(2.0))) / 2.0
```
So maybe that is triggering the error.  That is in `sciunit.scores` (around line 102).  Maybe try revising your working copy of `sciunit` to catch an exception in that statement and throw a different Exception, e.g. `"Exception('the line with erf in it')"`, and make sure you use that `sciunit` and then try again.  I'm not sure what the problem would be there (`self.score` should be some number, maybe positive, maybe negative, but any real number should be a good argument to `math.erf`.  You could try using import `cmath` instead of import `math` to handle complex numbers, but that seems like a kludge since why should `self.score` ever be complex?

**Comment by russelljjarvis** [comment]
AOK. I decided to just exclude neuron models that have a 0Amp Rheobase current, as I need to concentrate on generating figures for the presentation. Your comment above will be very useful documentation for the occasion when someone is able to look at this again.

**Comment by russelljjarvis** [comment]
As you allude to above its line [208 of sciunit scores](https://github.com/scidash/sciunit/blob/dev/sciunit/scores.py#L208)

If Rheobase current injection is 0.0pA then Ratio scores sort key gets fed in 0.0 as an argument but it can't handle it.


I finally tracked down this bug
In regular ipython3:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-c9c16424fc91> in <module>()
----> 1 math.log10(0.0)

ValueError: math domain error
```

An easy fix would be:
```
        if self.score != 0:
            return 1.0 - min(1,math.fabs(math.log10(self.score)))
        else:
            return 0.0
```
I think this captures the intended meaning, as math.log10(0.0) approaches -infinity, the absolute value of -inf would be inf, 1.0 would be smaller so it will be chosen by the min function `1.0-1.0=0.0` so I think its fine to return 0.0

However I am unsure about if returning 0.0 here is a fair error assignment that reflects the fitness of a gene that fires one spike with no current injection.

**Comment by russelljjarvis** [comment]
I am still seeing a related error to the one above, suggesting that the fix I proposed above is not a satisfactory solution.
An example of the stack trace is as follows:
```
  File "nsga.py", line 527, in main
    fitnesses = list(toolbox.map(toolbox.evaluate, pop, tuple_storage))
  File "nsga.py", line 211, in evaluate
    score = get_neab.suite.judge(model)#passing in model, changes the model
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.6-py3.5.egg/sciunit/__init__.py", line 431, in judge
    log('Score is <a style="color: rgb(%d,%d,%d)">' % score.color()
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.6-py3.5.egg/sciunit/__init__.py", line 521, in color
    value = self.sort_key
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.6-py3.5.egg/sciunit/scores.py", line 208, in sort_key
    return 1 - min(1,math.fabs(math.log10(self.score)))
ValueError: math domain error
Segmentation fault
```

**Comment by rgerkin** [comment]
@russelljjarvis Is this problem fixed?
