### ISSUE TITLE
scaling linear sum of errors and sciunit error for score 0.0

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/sciunit#43]
[Relating to this error too](https://github.com/scidash/sciunit/issues/41#issuecomment-291990921). I now believe the real problem was, if my rheobase search method didn't succeed in finding rheobase after 4 iterations it returned 0.0 instead of None. From outside the algorithm it looked like a value of 0.0Amps was found, but in fact nothing was found. Also the mistaken 0Amp return from the rheobase search was not able to yield an appropriately large error in sciunit, meaning that the GA would converge on values where no rheobase could be found. In other words this error propogated on through the GA, and it meant the GA could not learn rheobase very well.

My latest push to dev circumvents these problems.

**Comment by rgerkin** [comment]
@russelljjarvis Is this problem fixed now?
