### ISSUE TITLE
Git repository details automatically added to every object

### ISSUE THREAD

**Issue by rgerkin** [scidash/sciunit#53]
Put the commit # and origin of the current working copy into every model/test/capability created from a python session inside that working copy.

**Comment by apdavison** [comment]
You've probably already got something in mind for this, but here's some code I wrote previously which does some of this:
```python
import git

class Versioned(object):
    """
    A Mixin class for SciUnit model instances, which provides a version string
    based on the Git repository where the model is tracked.
    """

    def get_version(self):
        module = sys.modules[self.__module__]
        path = os.path.realpath(module.__path__[0])
        repo = git.Repo(path, search_parent_directories=True)
        head = repo.head
        version = head.commit.hexsha
        if repo.is_dirty():
            version += "*"
        return version
    version = property(get_version)
```

**Comment by rgerkin** [comment]
That's great!  I'll use it.

**Comment by rgerkin** [comment]
Implemented in 648c2d30e79f33c87389c165d358504815c38480

**Comment by apdavison** [comment]
Note that this gives you the commit # but not the repository origin

**Comment by rgerkin** [comment]
Remote URL support added.  See [here](https://github.com/scidash/sciunit/blob/master/sciunit/unit_test/core_tests.py#L484) for a complete example.
