### ISSUE TITLE
Reduce sig figs for Coveralls

### ISSUE THREAD

**Issue by gsarma** [scidash/sciunit#75]
Right now Coveralls uses 5 significant digits or something like that, which means that new pull requests don't pass the tests even if there is a minuscule drop in coverage.  Can we change this to just use whole number values and maybe set the threshold to 2-5%?  

@rgerkin

**Comment by rgerkin** [comment]
Is that an option in the documentation?  I don't really worry about coverage changes on PRs, anyway.

**Comment by rgerkin** [comment]
I increased the threshold for coveralls to report a failure, from any decrease > 0% to only decreases > 0.5%.
