### ISSUE TITLE
New method on suite to check capabilities of models against tests

### ISSUE THREAD

**Issue by gidili** [scidash/sciunit#79]
- [x] new method on suite called `.checkCapabilities`
- [x] will take as input a list model classes (or model instances)
- [x] Jupyter notebook example of how to load classes from module_paths and how to call suite.check with these

**Comment by rgerkin** [comment]
Example notebook in rgerkin/scidash-api@12dd8c7126f0215389bbaa6cd9549fc35ecd88a6.  Use latest sciunit dev branch.
