### ISSUE TITLE
local storing of test predictions

### ISSUE THREAD

**Issue by rgutzen** [scidash/sciunit#80]
Model predictions may be costly to compute and in some cases, they are recomputed multiple times. For example for testing against multiple data sets or for visualizations. Therefore, it would be useful to do the computation only the first time `generate_prediction()` is called and else recall the prediction from storage.

A very quick fix would be to generate a random hash upon test initialization and let the function `generate_prediction()` save to and load from `model.predictions[test_hash]`. But there is probably a more elegant way which so that the `generate_prediction()` function is still overwriteable by the user.

**Comment by rgerkin** [comment]
@rgutzen 
We have something like this implemented in NeuronUnit.  If you take a look at [this](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/cache_use.ipynb) notebook you can see how it works.  The cache itself is stored in a Backend class, and there are various backends to choose from when instantiating a NeuronUnit model (jNeuroML, NEURON, etc.)  It is implemented this way with the idea that the cache is not necessarily appropriate if switching to a new simulator for the same model.  

Anyway, it is stored according to model hash (by default), computed from the current state of the model (model parameters e.g. cell conductances + simulation parameters e.g. current injections) at the time it is run.  The cache is in memory by default, but can be turned off and on as demonstrated in the above notebook, as can disk caching.  

I could probably move all this into SciUnit as you described, although I would want to retain the ability to override caching at the level of generate_prediction and stored in the model with the caching at the level of simulation and stored in the backend as I described above.

**Comment by rgerkin** [comment]
@rgutzen I have moved this into SciUnit so you could try it out.  All you would have to do it create your own Backend class that derives from `sciunit.models.backends.Backend`.  Let me know if you want more details.
